### ISSUE TITLE
The shift only works manually, doesn't change when I login. Sunrise/sunset only works if the PC is turned on

### ISSUE THREAD

**Issue by KierPrev** [justjokiing/kshift#12]
For example, if I log in at 11 am, it stays at the Night theme, unless I switch it manually.
When the sunset time arrives, it indeed changes.

**Comment by KierPrev** [comment]
```
kshift -s
##################################
Kshift ENABLED:
 october   @ *-10-* 00:00:00
  night    @ *-*-* 18:22:00
   day     @ *-*-* 08:06:00

##################################
kshift local variables @/home/kier/.config/kshift/kshift.yml
##################################
location: ARXX1765 # Location Code from https://weather.codes/search
sunrise: '07:00'   # Default sunrise time, when time data cannot be accessed. These must be in quotes.
sunset: '19:00'    # Default sunset  time
rise_delay: 0      # Hour delay for sunrise, can be negative
set_delay: 0       # Hour delay for sunset
webdata: true      # Boolean for accessing web for time data
net_timeout: 10    # How long to wait for network timeout
themes:
  day:
    colorscheme: BreezeLight  # Check 'plasma-apply-colorscheme -l' for options
    icontheme: breeze
    wallpaper: /home/kier/Imágenes/day.jpg
    command: ''               # Runs command at theme activation
    time: sunrise             # Keywords 'sunrise', 'sunset', or ANY correct systemd 'OnCalendar' time
  night:
    colorscheme: BreezeDark
    icontheme: breeze-dark
    wallpaper: /home/kier/Imágenes/night.jpg
    command: ''
    time: 
      - sunset
  october:
    wallpaper: /usr/share/wallpapers/FallenLeaf/contents/images/2560x1600.jpg
    time: '*-10-* *:*:*'
    enable: false             # Disables theme, it will not run on time

```
